Controllers/ÜrünController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using MvcStok.Models.Entity;

namespace MVC_1.Controllers
{
    public class ÜrunController : Controller
    {
        // GET: Ürun
      MVCdbStokEntities db = new MVCdbStokEntities();
        public ActionResult Index()
        {
            var degerler = db.U_Table_1.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler =(from i in db.S_Table_1.ToList()
                                                select new SelectListItem
                                                { 
                                                Text=i.KATAGORIAD,
                                                Value= i.KATAGORIID.ToString()
                                                }).ToList();
            ViewBag.dgr=degerler;

            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(U_Table_1 p3)
        {
            var ktgr = db.S_Table_1.Where(i => i.KATAGORIID == p3.S_Table_1.KATAGORIID).FirstOrDefault();
            p3.S_Table_1 = ktgr;
            db.U_Table_1.Add(p3);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var urun = db.U_Table_1.Find(id);
            db.U_Table_1.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult yeni(int id)
        {
            var urn = db.U_Table_1.Find(id);
            return View("yeni", urn);
        }
        [HttpPost]
        public ActionResult Guncelle(U_Table_1 p1)
        {
            var urnu =db.U_Table_1.Where((i) => i.URUNID == p1.URUNID).FirstOrDefault();
            urnu.URUNAD=p1.URUNAD;
            urnu.MARKA=p1.MARKA;
            urnu.STOK=p1.STOK;
            urnu.FİYAT=p1.FİYAT;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Ürun/Index.cshtml
@using MvcStok.Models.Entity
@model List<U_Table_1>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>Urun ID</th>
        <th>Urun Adı</th>
        <th>Markası</th>
        <th>Kategorisi</th>
        <th>Fiyat</th>
        <th>Stok</th>
    </tr>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <td>@urn.URUNID</td>
                <td>@urn.URUNAD</td>
                <td>@urn.MARKA</td>
                <td>@urn.S_Table_1.KATAGORIAD</td>
                <td>@urn.STOK</td>
                <td>@urn.FİYAT</td>
                <td><a href="/Ürun/SIL/@urn.URUNID" class="btn btn-danger">SİL</a></td>
                <td><a href="/Ürun/Guncelle/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td>

            </tr>

        }
    </tbody>
</table>
<a href="/Ürun/UrunEkle" class="btn btn-primary">YENİ ÜRÜN EKLE</a>

Views/Ürun/UrunEkle.cshtml
@model MvcStok.Models.Entity.U_Table_1
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="URUNAD" />
       
        <label>Markası</label>
        <input type="text" class="form-control" name="MARKA" />

        <label>Kategori Seçiniz</label>
        @Html.DropDownListFor(m => m.S_Table_1.KATAGORIID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form form-control" })
        <label>Stok Adedi</label>
        <input type="text" class="form-control" name="STOK" />
        <label>Fiyatı</label>
        <input type="text" class="form-control" name="FİYAT" />
    
        <div style="margin-top:15px">
            <button class="btn btn-info">Ürün Ekle</button>
        </div>
    </div>
</form>

Views/Ürun/yeni.cshtml
@model MvcStok.Models.Entity.U_Table_1

@{
    ViewBag.Title = "yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Ürun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(i => i.URUNID)
        @Html.TextBoxFor(i => i.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.URUNAD)
        @Html.TextBoxFor(i => i.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.URUNAD)
        @Html.TextBoxFor(i => i.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.URUNAD)
        @Html.TextBoxFor(i => i.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.URUNAD)
        @Html.TextBoxFor(i => i.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.URUNAD)
        @Html.TextBoxFor(i => i.URUNAD, new { @class = "form-control" })
    </div>

    <div>
        <button class="btn btn-warning">Urun Güncelle</button>
    </div>
}