Controllers/MüşteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using MvcStok.Models.Entity;

namespace MVC_1.Controllers
{
    public class MüşteriController : Controller
    {
        // GET: Müşteri
        MVCdbStokEntities db = new MVCdbStokEntities(); 
        public ActionResult Index()
        {
            var degerler = db.M_Table_1.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(M_Table_1 p2)
        {
            db.M_Table_1.Add(p2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var müşteri=db.M_Table_1.Find(id);
            db.M_Table_1.Remove(müşteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var mus=db.M_Table_1.Find(id);
            return View("MusteriGetir", mus);
            
        }
        public ActionResult Guncelle(M_Table_1 p1)
        {
            var p = db.M_Table_1.Find(p1.MUSTERIID);
            p.MUSTERIAD = p1.MUSTERIAD;
            p.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Müşteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<M_Table_1>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table table-bordered">
    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri Adı</th>
        <th>Müşteri oyadı</th>

    </tr>
    <tbody>
        @foreach (var mstr in Model)
        {
            <tr>
                <td>@mstr.MUSTERIID</td>
                <td>@mstr.MUSTERIAD</td>
                <td>@mstr.MUSTERISOYAD</td>
                <td><a href="/Müşteri/SIL/@mstr.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/Müşteri/MusteriGetir/@mstr.MUSTERIID" class="btn btn-success">GÜNCELLE</td>
            </tr>

        }
    </tbody>
</table>
<a href="/Müşteri/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

Views/Müşteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.M_Table_1
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Müşteri", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(i => i.MUSTERIID)
                    @Html.TextBoxFor(i => i.MUSTERIID, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(i => i.MUSTERIAD)
                    @Html.TextBoxFor(i => i.MUSTERIAD, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(i => i.MUSTERISOYAD)
                    @Html.TextBoxFor(i => i.MUSTERISOYAD, new { @class = "form-control" })

                </div>
                <div>
                    <button class="btn btn-warning">Müşteri Güncelle</button>
                </div>
            }

Views/Müşteri/YeniMusteri.cshtml
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Müşteri Adı</label>
        <input type="text" class="form-control" name="MUSTERIAD" />
   
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
     
        <div style="margin-top:15px">
            <button class="btn btn-info">Müşteri Ekle</button>
        </div>
    </div>
</form>